"""Public SpaceTimePy v2 programmatic interface.

The web API should be implemented as an adapter over these services and DTOs,
not as a second route into the internal ORM model.
"""

from spacetimepy.core.serialization import (
    CustomPickler,
    CustomPicklerError,
    CustomPicklerProvider,
    DispatchTable,
    Reducer,
    SerializationError,
)

from .capture import (
    CaptureDeclaration,
    CaptureInterface,
    CaptureMode,
    CaptureRegistry,
    CaptureReturnContext,
    CaptureStartContext,
    RecordingHandle,
    ReturnHook,
    StartHook,
    clear_capture_declarations,
    external,
    function,
    line,
    support,
    unregister_capture_declaration,
)
from .data import (
    BranchDTO,
    BranchSummaryDTO,
    CodeDefinitionDTO,
    ExternalInteractionDTO,
    FunctionCallDTO,
    SessionDTO,
    StackSnapshotDTO,
    StepDTO,
    StoredValueDTO,
    TraceConsistencyError,
    TraceData,
    TraceDataError,
    TraceNotFoundError,
)
from .replay import (
    ExternalInteractionScript,
    RecordedExternalInteraction,
    ReplayContext,
    ReplayDivergenceError,
    ReplayError,
    ReplayInterface,
    ReplayResult,
)
from .runtime import SpaceTime, open_spacetime

__all__ = [
    "BranchDTO",
    "BranchSummaryDTO",
    "CaptureDeclaration",
    "CaptureInterface",
    "CaptureMode",
    "CaptureRegistry",
    "CaptureReturnContext",
    "CaptureStartContext",
    "CodeDefinitionDTO",
    "CustomPickler",
    "CustomPicklerError",
    "CustomPicklerProvider",
    "DispatchTable",
    "ExternalInteractionDTO",
    "ExternalInteractionScript",
    "FunctionCallDTO",
    "RecordedExternalInteraction",
    "RecordingHandle",
    "ReturnHook",
    "ReplayContext",
    "ReplayDivergenceError",
    "ReplayError",
    "ReplayInterface",
    "ReplayResult",
    "Reducer",
    "SessionDTO",
    "SerializationError",
    "SpaceTime",
    "StackSnapshotDTO",
    "StepDTO",
    "StoredValueDTO",
    "StartHook",
    "TraceConsistencyError",
    "TraceData",
    "TraceDataError",
    "TraceNotFoundError",
    "clear_capture_declarations",
    "external",
    "function",
    "line",
    "open_spacetime",
    "support",
    "unregister_capture_declaration",
]
